### ISSUE TITLE
4th test fail

### ISSUE THREAD

**Issue by kirillgolovko** [adamheinrich/native-utils#12]
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running cz.adamh.utils.NativeUtilsTest
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.039 sec <<< FAILURE! - in cz.adamh.utils.NativeUtilsTest
testLoadLibraryNullPath(cz.adamh.utils.NativeUtilsTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.NullPointerException> but was<java.lang.IllegalArgumentException>
	at cz.adamh.utils.NativeUtils.loadLibraryFromJar(NativeUtils.java:78)
	at cz.adamh.utils.NativeUtilsTest.testLoadLibraryNullPath(NativeUtilsTest.java:27)


Results :

Tests in error: 
  NativeUtilsTest.testLoadLibraryNullPath »  Unexpected exception, expected<java...

Tests run: 4, Failures: 0, Errors: 1, Skipped: 0
```

Got this while running maven goal on your project. I guess the IllegalArgumentException is ok because of main sources, but the tests maybe need to be corrected.

**Comment by adamheinrich** [comment]
@kirillgolovko Hi, thank you for reporting! Could you please confirm it is fixed now?
